a=float(input("enter first number:"))
b=float(input("enter second number:"))
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("remainder:",a%b)
print("division:",a/b)
